- name: Instalacja docker-compose oraz docker
  pip:
    name:
      - docker
      - docker-compose

- name: git checkout
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- Name: docker-compose
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes
